# Generated by Django 2.1a1 on 2018-11-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinerama_app', '0002_auto_20181121_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='actors_contry',
            new_name='actors_country',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='ganre_name',
            new_name='genre_name',
        ),
        migrations.AddField(
            model_name='actor',
            name='actor_photo',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producer',
            name='producer_photo',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
